name: Developer Resource
markdown: redcarpet
pygments: true
github: https://www.github.com/LoyalSphere
baseurl: /stellar-dev
about: >
       This is a portal for all developer resources that can be used to
       create stunning loyalty applications using the StellarLoyalty Service.

urls:
    - text: github
      url: https://github.com/LoyalSphere
    - text: email
      url: mailto:developer@stellarloyalty.com
    - text: corporate site
      url: http://www.stellarlotyalty.com

collections:
    ios_sdk:
      output: true
    android_sdk:
      output: true
    js_sdk:
      output: true